language: python
python:
  - 2.7
  - 3.6

env:
  - CFLAGS=-I/usr/include/gdal

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -y install libgdal-dev libstdc++6-4.6-dev

install:
  - pip install --global-option=build_ext --global-option='-USQLITE_OMIT_LOAD_EXTENSION' pysqlite
  - pip install coveralls GDAL==2.1.0
  - pip install mapnik==0.1 || echo 'optional'
  - pip install -r requirements.txt

script: make coverage
after_success: coveralls
