dist: xenial
addons:
  apt:
    sources:
      - ppa:ubuntugis/ubuntugis-unstable
    packages:
      - libgdal-dev

language: python
python:
  - 2.7
  - 3.6

env:
  - CFLAGS=-I/usr/include/gdal

install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then pip install --global-option=build_ext --global-option='-USQLITE_OMIT_LOAD_EXTENSION' pysqlite; fi
  - pip install coveralls Pillow GDAL==2.1.0
  - pip install mapnik==0.1 || echo 'optional'
  - pip install -r requirements.txt

script: make coverage
after_success: coveralls
